version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      pydantic:
        patterns:
          - "pydantic*"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"